"""Default BPR bank list provided by user."""

BANK_LIST = [
    "PT Bank Perekonomian Rakyat Duta Bali",
    "PT Bank Perekonomian Rakyat Dana Karya Nusa",
    "PT Bank Perekonomian Rakyat Cahaya Arthabali",
    "PT Bank Perekonomian Rakyat Wahyu Nirmala",
    "PT Bank Perekonomian Rakyat Bukit Tanjung",
    "PT Bank Perekonomian Rakyat Karuna Ramanda Sejahtera",
    "PT Bank Perekonomian Rakyat Sari Dananiaga",
    "PT Bank Perekonomian Rakyat Bank Buleleng 45 (Perseroda)",
    "PT Bank Perekonomian Rakyat Indra Candra",
    "PT Bank Perekonomian Rakyat Bank Daerah Bangli (Perseroda)",
    "PT Bank Perekonomian Rakyat Karya Artha Sejahtera Indonesia",
    "PT Bank Perekonomian Rakyat Kusuma Mandala Jaya",
    "PT Bank Perekonomian Rakyat Kertha Warga",
    "PT Bank Perekonomian Rakyat Amerta Sari",
    "PT Bank Perekonomian Rakyat Parasari",
    "PT Bank Perekonomian Rakyat Pasarraya Kuta",
    "PT Bank Perekonomian Rakyat Pedungan",
    "PT Bank Perekonomian Rakyat Penebel",
    "PT Bank Perekonomian Rakyat Desa Sangeh",
    "PT Bank Perekonomian Rakyat Desa Sanur",
    "PT Bank Perekonomian Rakyat Sekolah Perhotelan Bali",
    "PT Bank Perekonomian Rakyat Sari Sedana",
    "PT Bank Perekonomian Rakyat Sedana Murni",
    "PT Bank Perekonomian Rakyat Sedana Yasa",
    "PT Bank Perekonomian Rakyat Tri Darma Putri",
    "PT Bank Perekonomian Rakyat Pande Artha Dewata",
    "PT Bank Perekonomian Rakyat Bank Daerah Gianyar (Perseroda)",
    "PT Bank Perekonomian Rakyat Nusamba Kubutambahan",
    "PT Bank Perekonomian Rakyat Nusamba Manggis",
    "PT Bank Perekonomian Rakyat Nusamba Mengwi",
    "PT Bank Perekonomian Rakyat Nusamba Tegallalang",
    "PT Bank Perekonomian Rakyat Krisna Yuna Dana",
    "PT Bank Perekonomian Rakyat Pusaka",
    "PT Bank Perekonomian Rakyat Sadhu Artha",
    "PT Bank Perekonomian Rakyat Puskusa Bali Dwipa",
    "PT Bank Perekonomian Rakyat Adi Jaya Mulia",
    "PT Bank Perekonomian Rakyat Tata Anjung Sari",
    "PT Bank Perekonomian Rakyat Bunga Sutra Mas",
    "PT Bank Perekonomian Rakyat Tapa",
    "PT Bank Perekonomian Rakyat Sandi Raya Utama",
    "PT Bank Perekonomian Rakyat Karya Sari Sedana",
    "PT Bank Perekonomian Rakyat Sari Werdhi Sedana",
    "PT Bank Perekonomian Rakyat Sari Wira Tama",
    "PT Bank Perekonomian Rakyat Sukawati Pancakanti",
    "PT Bank Perekonomian Rakyat Suadana",
    "PT Bank Perekonomian Rakyat Nur Abadi",
    "PT Bank Perekonomian Rakyat Lestari Bali",
    "PT Bank Perekonomian Rakyat Maha Bhoga Marga",
    "PT Bank Perekonomian Rakyat Sri Partha Bali",
    "PT Bank Perekonomian Rakyat Artha Bali Jaya",
    "PT Bank Perekonomian Rakyat Shri Gangga Bali",
    "PT Bank Perekonomian Rakyat Tish",
    "PT Bank Perekonomian Rakyat Ashi",
    "PT Bank Perekonomian Rakyat Sinar Kuta",
    "PT Bank Perekonomian Rakyat Jaya Kerti",
    "PT Bank Perekonomian Rakyat Urban Bali",
    "PT Bank Perekonomian Rakyat Cerdas",
    "PT Bank Perekonomian Rakyat Mambal",
    "PT Bank Perekonomian Rakyat Saraswati Eka Bumi",
    "PT Bank Perekonomian Rakyat Artha Adyamurthi",
    "PT Bank Perekonomian Rakyat Restu Dewata",
    "PT Bank Perekonomian Rakyat Saudaraku",
    "PT Bank Perekonomian Rakyat Prima Dewata",
    "PT Bank Perekonomian Rakyat Prisma Bali",
    "PT Bank Perekonomian Rakyat Bumi Prima Dana",
    "PT Bank Perekonomian Rakyat Surya Natapala",
    "PT Bank Perekonomian Rakyat Kamadana",
    "PT Bank Perekonomian Rakyat Sinar Kuta Mulia",
    "PT Bank Perekonomian Rakyat Dharmawarga Utama",
    "PT Bank Perekonomian Rakyat Jero Anom",
    "PT Bank Perekonomian Rakyat Cahaya Bina Putra",
    "PT Bank Perekonomian Rakyat Kita Centradana",
    "PT Bank Perekonomian Rakyat Sinar Puteramas",
    "PT Bank Perekonomian Rakyat Siwi Sedana",
    "PT Bank Perekonomian Rakyat Luhur Damai",
    "PT Bank Perekonomian Rakyat Tulus",
    "PT Bank Perekonomian Rakyat Bayudhana",
    "PT Bank Perekonomian Rakyat Parasari Urati",
    "PT Bank Perekonomian Rakyat Artha Sinar Raharja Indonesia",
    "PT Bank Perekonomian Rakyat Bank Kertiawan",
    "PT Bank Perekonomian Rakyat Sentral Ekonomi Nusantara",
    "PT Bank Perekonomian Rakyat Santi Pala",
    "PT Bank Perekonomian Rakyat Mayun Utama Perdana",
    "PT Bank Perekonomian Rakyat Suryajaya Ubud",
    "PT Bank Perekonomian Rakyat Picu Manunggal Sejahtera",
    "PT Bank Perekonomian Rakyat Dinar Jagad",
    "PT Bank Perekonomian Rakyat Ulatidana Rahayu",
    "PT Bank Perekonomian Rakyat Mertha Sedana",
    "PT Bank Perekonomian Rakyat Padma",
    "PT Bank Perekonomian Rakyat Gisawa",
    "PT Bank Perekonomian Rakyat Suryajaya Kubutambahan",
    "PT Bank Perekonomian Rakyat Permata Sedana",
    "PT Bank Perekonomian Rakyat Urip Kalantas",
    "PT Bank Perekonomian Rakyat Cahaya Binawerdi",
    "PT Bank Perekonomian Rakyat SaPTacristy Utama",
    "PT Bank Perekonomian Rakyat Naga",
    "PT Bank Perekonomian Rakyat Danamaster Dewata",
    "PT Bank Perekonomian Rakyat Suar Artha Dharma",
    "PT Bank Perekonomian Rakyat Mas Giri Wangi",
    "PT Bank Perekonomian Rakyat Sadana Utama Bali",
    "PT Bank Perekonomian Rakyat Megah Raharja Berdaya",
    "PT Bank Perekonomian Rakyat Nusapanida Kuta",
    "PT Bank Perekonomian Rakyat Hari Depan",
    "PT Bank Perekonomian Rakyat Khrisna Darma Adipala",
    "PT Bank Perekonomian Rakyat Bali Dananiaga",
    "PT Bank Perekonomian Rakyat Aruna Nirmaladuta",
    "PT Bank Perekonomian Rakyat Varis Mandiri",
    "PT Bank Perekonomian Rakyat Arthabudaya",
    "PT Bank Perekonomian Rakyat Partakencana Tohpati",
    "PT Bank Perekonomian Rakyat Gianyar Partasedana",
    "PT Bank Perekonomian Rakyat Hoki",
    "PT Bank Perekonomian Rakyat Mitra Bali Srisedana Mandiri",
    "PT Bank Perekonomian Rakyat Mitra Bali Artha Mandiri",
    "PT Bank Perekonomian Rakyat Mitra Balijaya Mandiri",
    "PT Bank Perekonomian Rakyat Mitra Bali Mandiri",
    "PT Bank Perekonomian Rakyat Kusemas Dana Mandiri",
    "PT Bank Perekonomian Rakyat Angsa Sedanayoga",
    "PT Bank Perekonomian Rakyat Kanaya",
    "PT Bank Perekonomian Rakyat Mitra Bali Muktijaya Mandiri",
    "PT Bank Perekonomian Rakyat Kita",
    "PT Bank Perekonomian Rakyat Balaguna Perasta",
    "PT Bank Perekonomian Rakyat Mulia Wacana",
    "PT Bank Perekonomian Rakyat Kancana Dewata Mahadahana",
    "PT Bank Perekonomian Rakyat Raga Jayatama",
    "PT Bank Perekonomian Rakyat Dewata Candradana",
    "PT Bank Perekonomian Rakyat Eka Ayu Artha Bhuwana",
    "PT Bank Perekonomian Rakyat Sari Jaya Sedana",
]
